
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace February27th_EntityFramework
{

using System;
    using System.Collections.Generic;
    
public partial class Enrollment
{

    public int Id { get; set; }

    public int StudentID { get; set; }

    public int InstructorID { get; set; }

    public double Grade { get; set; }



    public virtual Student Student { get; set; }

    public virtual Instructor Instructor { get; set; }

}

}
